kind: pipeline
type: exec
name: Build all hosts

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
- name: Show flake info
  commands:
  - eval "$(ssh-agent -s)"
  - echo $TEST_KEY
  - echo "${SSH_DEPLOY_KEY}" | ssh-add -
  - nix --experimental-features "nix-command flakes" flake show
  - nix --experimental-features "nix-command flakes" flake metadata
- name: Run flake checks
  commands:
  - nix --experimental-features "nix-command flakes" flake check --show-trace
- name: Build kartoffel
  commands:
  - nix build -v -L '.#nixosConfigurations.kartoffel.config.system.build.toplevel'
- name: Build ahorn
  commands:
  - nix build -v -L '.#nixosConfigurations.ahorn.config.system.build.toplevel'
- name: Build porree
  commands:
  - nix build -v -L '.#nixosConfigurations.porree.config.system.build.toplevel'
- name: Build kfbox
  commands:
  - nix build -v -L '.#nixosConfigurations.kfbox.config.system.build.toplevel'
- name: Build bob
  commands:
  - nix build -v -L '.#nixosConfigurations.bob.config.system.build.toplevel'
- name: Build birne
  commands:
  - nix build -v -L '.#nixosConfigurations.birne.config.system.build.toplevel'
- name: Notify
  commands:
    - 'nix run "github:mic92/nur-packages#irc-announce" -- irc.hackint.org 6697 bob-the-builder "#lounge-rocks-log" 1 "🛠️ [$DRONE_REPO] ($DRONE_BUILD_EVENT) $DRONE_BUILD_STATUS | $DRONE_COMMIT_MESSAGE" || true'
  environment:
    LOGNAME: drone
    SSH_DEPLOY_KEY:
      from_secret: gitea_deploy_key
    TEST_KEY:
      from_secret: test_key
  when:
    status:
    - failure
    - success

trigger:
  branch:
  - main
  - test-sops-nix
  event:
  - push

---

kind: secret
name: test_key
data: adJiLSlrrr41uE8ScjKZETKUmPACgX4N77Z7KZheBjs9LGuP45eihu+GDGvxKZxNHY5n0U0Gsc/ghfyBTctzzrOz7T+zprtYUsm1H8c38d92ZZbPidJy4fsdQUP11AtrUliHs17xo7fS15/vsaCULiWNZ0goII0TFX3PK10/2dTZpTGn7cY+jiPy7sg/m+0HiqcCqDdlBLo4NIeXJiH/QWEz162Ex9L5HCHHRgviR5L2dDPmbhWUl0yU8nc3fxYee/ftSsv3cmkUcm6nuJbs76bf87aecsYJfxf30MjsW1Y9hxh4K5UTovYNWXradF/1Czqey5wcqrAVZApW+3YngSCljClAgGvqoxKSlhpIWeLxgmkyh4qiWcbJd/auQ5jXZcnoyubtwEbEX/EWX5OhnIaNcCxiP75eHPm9WyGedosA53CkiphgT/jjn6F0TIHicX9GjUN6vdISKw95SoGAw5QaPU0HOBqP0BN+RM5BdNZiv8bCWHvnk4RFluCZMNf1D1e+MWvw14yfoUx3xOJrAxBWqs5D1Zvm7LeDy2fhyphWFm1Cn1m8PLC7QDhuBAvl3dwNnoIiCA5G3IyUxThyXEhlb2792nasFV36urXBqRkqJi9bB5sG8QmPaD9FUjVCVrQl9gDKcL5zaYfjfUAtKIrnHymHK6UNfCWOCi0TMYlG0M9hQrIVSZluOy1MZvmel5YKcD4x/ZlHT6JxzA+BeEfgvjGZEKFgjEHX/09tUInz+w5ObPeP7SgswLASH1DCOvD/eY8K3Z53TepxOPs1smvQcJ0uR4zghvQTvmZ4dfnyetOdrbp7JsVFf8U8EYislDKzFfwGoWzbwon97A63IkIJohLN+rw5X5RPkxcxhdALTNSRhYPEtM0qJOIZxCUKf5QGn1/xx1SumBT5wlUYXI+6cdoSPy9a8QYdONsegPpfIFoVHeibO+rfr82iiltPb0keXsZWDZdZBlF4FeSgQDtnsknMb/jHY9pdznBaChDNloJGjrB2b9XcGhXRgf4gyuV3rwSI3pjDsXD2XYXqWHx+hALZwg7O1t2KziiR3dD+65QEEueW1uK6BJbx17VJpAX5eIgTexcVC3RwkYoy6PVMP4LdKzSlGKRr9N+Rqvb7kFa8azStaoHRtU/nc2Luxz0XjEM9mBAYmLBEfrZq+s3jdn4SHgX8adJEtBSy4XgLU6FjN9Vr0xpBoeWZzN87CGZHzDpnccqHevqyWDm2VgEuLpJl8ItsjTG2295W/XIZn5OcdbJNbr7aWkoJsEMEhltpxa1S2MCK5OO9TICX9e8danrs8gpX/KV4+BZLd7u0B9OWm9fuSzlVY7+AmRr51+/hY1WRFUjRrgRV9AkVwUIWdJwVy7i7K7DTvIjCfY4T1siCN/B4xUig1tqc6Yo6oPbOfGk/bYPbi3REGYrTJqdMWoWB/mYTIgs8oPBKXILEV8UX3XngejiQQdApeRDO7LKnQtydBMT7j25Sj8U75Ol/ZP6rwLqYjjBxpfo4ZYAzo5NBGQKAR5QwufJ0ZpJdJOCicPtb9mTG3nWWewcuNJdeo8vi2x2GCZogytsjOL90KkmnidPN4VPU6rnmPOyhKq4V5RTseE3gmNddeNhL8/qzdiFwXpvFKheo5j8hclW0ObLaR44OEEou8L/rrPQCfazkRKwSppi5ze3OVU5+joWUPE7krSnZA5ZwJiZFuI9Ogx2+6Q8N0UENEZNhfKu1XxroCc/Oo0tPj0cZQ8e6M2AS0eRYTq+6w+UA8KOPy5PxBp41f7Gsl6hy+ta34fjSE2IqoS/4cCy+l20QCOXK/3vs1PeZ312nzzm82FBACCY42cH+fykvvcXM87NQFHmZstmZEv4kwm1gc72Y8Qt0uMLvemLMvga9IJfylwxZpJeODToNyzU0IbCxEHxNizadpFaWDj54ZybEggxzqiidbp7azTAQ3BFQ2mhUKchZT43YM2HDP0qqAeib1TL+yBU5G3qDYG8TutQ/1IolAS1eA8VN/jbG/cecWJ6BIsqNpFGeN5UGlq7kj8ze9gLcvfTDVRhLUP8cDsc5LTnjFgd7Re8f8BlKeZCtYyyhSi7ul0c+5+IOK285YOu1VmseIJeBkTysanjiCpSODwbhnS47D3Lv7To4dAQrDPlVxx59byUea9B9WlV9rXx4whQpRaTc5PlUsubwio1o4JqdlJ1SZV9Ct4EEWT8FmJv7AiNoFJ5tsMSLYLZJr2uBK8MbjCBD1YSpq7IXXAKUaMQM41uTowsVHkqglgur+6uGRSILKBpVFGvXe7IZAPbyQPyaTi2dmVr/AjcoUcA67opYM13bZ9ARCHrEeyQcq7eZdgx2YSCoUk0vYyc9uFubti3DbFUscylqxaP/eyqU/cZyzwRomWJ+L3Rg3QuBPf2ovhEDlSGBLNs0Sv2gwc3iR1C1TdXbvWxoGEPgWYgclULJcLK+DTEb0XqTuZi6KdFSzasKZpSYyWia/zZYTtZ7hLAHyiQjGTaifi/4snuTJs84xx/xPionsKc3cJQDXwq7vqoKLpcckxLlTgV6L2dJSVGVkZ0DrNj0ykEru6f5C96ZDW4vJWPue9WpcXHguw2Re5P7MqewRW+grri7I1BhuMeo0cQIdQV3k48ayJhe2yubaq4TyY6oQCOge+IUD8CKGIZVizMHHbghpzBn7fVWnVDvd8bmgZE2naLHXM9KrHIDkTg1DaqkDOOxzR76weE3HcJ6DdEGWQ6GCWyd/QS+WuumtI7LKCb5MIxQxH0jYU9jkN14wWTMMBFNWrAQawIWAoyCTMJwih2a6pAycHJwTrtD5o0kAKV6OIJMoTAM37Dtlnz5sCt4jC0Q7pMd4zdpEa5fsJTrfVNBySFlWSNvCL+eyzBR+7/BwaHiaHbCsN7KlOgijNNcI3JtK8oMn79prneTRAHAGy7gVna842xjEfEju+CjqNbFaP0RdJSimDOjk905YoIP6QFudo2TiyLMb1T9di52jkdZBP/F47Bx7vHJVgU++kQMifSH3f8U6KETQWOW0REH6Obpg/FxFIS8/1YH1uSszuwThjOkRBCYLevvd5diRvvc2Z6ksKWy8+sJtzGdzfxgF4HTY3R2D43OqxVAxSgA22v0Xs3oFdAkuLNwmrJo1SLb4JVgd+4P7XXDjlb6YhF/yrvteEL/EU0dxySQHSWL11IclyyPHiIqfDMX13QpDD2ZWPZywDJDMR5lpFJS2K5K06nh5zi5aTkGkoO7b7tusEx0ni+ilo3y7WxCku011Ll2GDbKMpccibpLjKdl14OElubdnQVcsLcAk4YsOHoRblulnG8XBEnL+KlVUIy5rYVup3puSUnxl7KMsoaGRpM72r0dqIKVF1p6whnxrupA55ObEy4a/9XKh+ScQfLJgrUbNEV114C9uvyQ5Qj3ruLxeR3IY1dKlu3g0ebj/2+vkGO32YHORbHafZJvMTa+Kv4WNL16Z56EJAR6Y6kE+yrGkhacZJcm7fQ=


---

kind: secret
name: gitea_deploy_key
data: iBrvbXBQwubLz7gYlRFC8uDRjMtIRmmqGwJ9eC3iMbMxXijFjI270OE4mUkPtq5fFny2Vak/VNqKED3yWzSQ9m4lC3ho4pQs6ahRs1vBNj6YddhichI9Yo0p5LoK4e/gfHfqIOa761CzxXyAY85RmBA8Q21HvLGzPOu0ARDxo9rxjHIefzQeIMyborqSpS9+eHhYxJfq+89F1/gRenYAWbCpsynnlZXMyxPA4Yox3+cWyH37d4mYbqfB6Sb1H2rxaXWL2MIIBM+hr1IsB/+/uPshHEsPtSMmYwO1ZfJA0Mqs1O9UifFkMd3qUR5ZBgc1BlAWYSCMxtKdTUEY01aScdcNgbF5oKe746X78BwzPprAP443AnW0cbyaOB3baA5sXpeKVwPQxxCJQIrkmAVTQEpWacO3XsBbpsuhQ6nsFgFazwd4N2tAk3F4D/CsH2CoxghLx1YJUWHg2yaMouxeyWWRf97Bg0VnNuXcskK2qqJIBmNMef6ukj4BsN4qFTaUbodPduayu1Ygf+gEJ1dvOGjoPH1SiwS+dTm0OsSSUjCKbqWkvV2Oh2C1xw==

---
kind: pipeline
type: docker
name: Update Flakes

steps:
- name: Update flake.lock
  image: nixpkgs/nix-flakes
  commands:
  - nix flake update
  environment:
    NIX_PATH: nixpkgs=channel:nixos-unstable

- name: Push updated flake.lock
  image: appleboy/drone-git-push
  settings:
    branch: update-flake
    remote: git@github.com:pinpox/nixos.git
    force: true
    commit: true
    commit_message: "❄ Update flake.lock"
    ssh_key:
      from_secret: deploy_key

trigger:
  event:
  - cron
  cron:
  - daily

