kind: pipeline
type: exec
name: Build all hosts

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
- name: Show flake info
  commands:
  - eval "$(ssh-agent -s)"
  - ssh-add - <<< $SSH_DEPLOY_KEY
  - mkdir ~/.ssh
  - echo 'git.lounge.rocks ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDhdkTwMnd0mp+nUF95/JOKXG2HL/NndrPAPTKy3YzGv/Joa3kvMHFlbQM3AR2wohzyAw88CgxuLGZq6WuKjkE1CayFrDqs5Gum5kjx3ULFr2xP6kaeljMC2HIwYfqMtDE/4ELvp8ryUwyrOFPXxoiDrepFAby4wyx2s6CkQPKa36S72cFYgIVf8W3bdgFExxAI/bBrDHkN2k+nfrZ58LT4SFaw19ZSOmhn14LcFb8X1vjj2gMjmfRGMlHl9DlkPSYQcZlY8u+lgO69FF3hGP+S8PT0JIwjKRGtAKOLi0IXTXfl/89LWTGfE9vOP59ovAVE/v5Zzvf07/1nCdlQx+VuEpNkSNYbopPnLT+sixjMj5AMMWHdcbp8XkXZSxuDUHpW9yfpeoLV7Z2JT2iTXqvx0rVAeTmjqfKHfuDiJdWPnJOqG9B2jAMN6l4RegfLP7D7NnIb52ypjYQXFZfFiy4I2pgKHfXJHpK1GJ7AAGE6PRfPPPid3NMii8lEnR9u7SqHZRMy/59ou5X5sbgaeS9WL37APZzV4aqPCwGnKD0dFrmBrvyBgge5nu6rSm8fbdVeXfQfCSlN/AjqijBB+BOzm32kIM0a5xhxfI2LZD8Gh5a1a287dFQV1aK/5RsF0zYqRHUozhIhV9rWwi/hUOaPUGFBBQxXbYPtneVw73kghw==' > $HOME/.ssh/known_hosts
  # - echo 'git.lounge.rocks ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDtJHqD/P0yVmCopIy2CHqYx09f3l0dzbo2ak+VtXC9i' >> 
  # - ssh-keyscan git.lounge.rocks >> ~/.ssh/known_hosts
  # - ssh-keyscan -H git.lounge.rocks >> ~/.ssh/known_hosts
  # - ssh-keyscan -H lounge.rocks >> ~/.ssh/known_hosts
  # - ssh-keyscan -H github.com >> ~/.ssh/known_hosts
  - cat ~/.ssh/known_hosts
  - chmod 600 ~/.ssh/known_hosts
  - echo "CLONING"
  - echo $HOME
  - whoami
  - git clone git@git.lounge.rocks:pinpox/nixos-secrets.git
  - nix --experimental-features "nix-command flakes" flake show
  - nix --experimental-features "nix-command flakes" flake metadata
  - nix --experimental-features "nix-command flakes" flake check --show-trace
  environment:
    LOGNAME: drone
    SSH_DEPLOY_KEY:
      from_secret: gitea_deploy_key

- name: Run flake checks
  commands:
  - nix --experimental-features "nix-command flakes" flake check --show-trace
- name: Build kartoffel
  commands:
  - nix build -v -L '.#nixosConfigurations.kartoffel.config.system.build.toplevel'
- name: Build ahorn
  commands:
  - nix build -v -L '.#nixosConfigurations.ahorn.config.system.build.toplevel'
- name: Build porree
  commands:
  - nix build -v -L '.#nixosConfigurations.porree.config.system.build.toplevel'
- name: Build kfbox
  commands:
  - nix build -v -L '.#nixosConfigurations.kfbox.config.system.build.toplevel'
- name: Build bob
  commands:
  - nix build -v -L '.#nixosConfigurations.bob.config.system.build.toplevel'
- name: Build birne
  commands:
  - nix build -v -L '.#nixosConfigurations.birne.config.system.build.toplevel'
- name: Notify
  commands:
    - 'nix run "github:mic92/nur-packages#irc-announce" -- irc.hackint.org 6697 bob-the-builder "#lounge-rocks-log" 1 "🛠️ [$DRONE_REPO] ($DRONE_BUILD_EVENT) $DRONE_BUILD_STATUS | $DRONE_COMMIT_MESSAGE" || true'
  when:
    status:
    - failure
    - success

trigger:
  branch:
  - main
  - test-sops-nix
  event:
  - push

---

kind: secret
name: gitea_deploy_key
data: xo0uUgkadMfxn9MdF6CbXgPpzQF4M6DPCKk3g3l0EfpfgnagnrrFCJO1LHr8Mr1V0ek78TdUpFTbcj4X7m9d8AEJhj/yzGTyiwqDo8fbqgQEGAMiM6mwlW/4+3UKOL1hrJvUnWOZMSoXKs0nsgxPlXjHz1b9p/iWL67QYwY6JkFedfLBnt0qhBB54XT78Hsm5E4m5h8pmBrreery+boEC5lkDmZAeJT8Fk7abytLx8JTacGtDWUVWuzlSK4FgwDNGRhbhvRi+2trdpa7wJ9rMK0F36z/VOwXwFd2QY69CpngBRu0BI8JVgE2vBdC5li3OtCv7RbEpqvAv+uCxyPtC+M4RoW5O5jAFXw8H5LJfCfeUhCXihoIPqfJ+6CPBZMOVekSfLqKX2Qlr/r3GquNkrZ1lProrLQhDDQfEIvbkcSPjqA9gCyGZ47oOKf2NUFpr8G3y5xSWjBEuK81kt69gnTYvv/2JqGkMtekctBAPYeR/PGyQ9ZUV606HPXRs6t1BdBh0/Uf1so29p5MwrkIeJNlyn2a2yNuIrsBQoDATmEiYw3pXfqyR0ndyg==

---
kind: pipeline
type: docker
name: Update Flakes

steps:
- name: Update flake.lock
  image: nixpkgs/nix-flakes
  commands:
  - nix flake update
  environment:
    NIX_PATH: nixpkgs=channel:nixos-unstable

- name: Push updated flake.lock
  image: appleboy/drone-git-push
  settings:
    branch: update-flake
    remote: git@github.com:pinpox/nixos.git
    force: true
    commit: true
    commit_message: "❄ Update flake.lock"
    ssh_key:
      from_secret: deploy_key

trigger:
  event:
  - cron
  cron:
  - daily

